### ISSUE TITLE
Illegal State Exception error

### ISSUE THREAD

**Issue by gwynhefar** [kappa-maintainer/Sound-Physics#3]
No crash, but my log is spammed with these errors.  I'm using SP1.1.1 for Minecraft 1.12.2  Any help would be appreciated - I'm having serious performance issues and I'm trying to narrow down what's causing it by investigating every error I see.

[01:35:31] [Thread-53/ERROR] [soundphysics]: Deadlock detected, avoiding it by throwing exception
01:35:31.795
game
[01:35:31] [Thread-53/ERROR] [soundphysics]: Error while evaluation environment:
01:35:31.795
game
java.lang.IllegalStateException: Player's Data Mananger is write locked
01:35:31.795
game
at com.sonicether.soundphysics.SoundPhysics.getPlayerEyeHeight(SoundPhysics.java:492) ~[SoundPhysics.class:?]
01:35:31.795
game
at com.sonicether.soundphysics.SoundPhysics.evaluateEnvironment(SoundPhysics.java:520) [SoundPhysics.class:?]
01:35:31.795
game
at com.sonicether.soundphysics.SoundPhysics.onPlaySound(SoundPhysics.java:319) [SoundPhysics.class:?]
01:35:31.795
game
at com.sonicether.soundphysics.SoundPhysics.onPlaySound(SoundPhysics.java:277) [SoundPhysics.class:?]
01:35:31.795
game
at paulscode.sound.libraries.SourceLWJGLOpenAL.handler$zif000$injectPlay(SourceLWJGLOpenAL.java:873) [SourceLWJGLOpenAL.class:?]
01:35:31.795
game
at paulscode.sound.libraries.SourceLWJGLOpenAL.play(SourceLWJGLOpenAL.java:671) [SourceLWJGLOpenAL.class:?]
01:35:31.795
game
at paulscode.sound.Library.play(Library.java:706) [Library.class:?]
01:35:31.795
game
at paulscode.sound.Library.play(Library.java:675) [Library.class:?]
01:35:31.795
game
at paulscode.sound.SoundSystem.CommandPlay(SoundSystem.java:2076) [SoundSystem.class:?]
01:35:31.795
game
at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2599) [SoundSystem.class:?]
01:35:31.795
game
at paulscode.sound.CommandThread.run(CommandThread.java:121) [CommandThread.class:?]

**Comment by kappa-maintainer** [comment]
Need full log and modlist
It seems a mod kept locking player's datamanager

**Comment by kappa-maintainer** [comment]
No response for 180 days + won't spam log now
