### ISSUE TITLE
Game suddenly froze

### ISSUE THREAD

**Issue by Margatroidu** [kappa-maintainer/Sound-Physics#9]
When I fly on elytra my game suddenly crashes and as logs write it is because of sound physics.

Two important points:
- This is E2EE modpack
- And it's not this fork of a mod. The modpack uses an early fork, but I suppose this problem could be here as well.

Any ideas why this is happening?

Logs:
[message.txt](https://github.com/user-attachments/files/17121074/message.txt)

**Comment by kappa-maintainer** [comment]
Crash report? There's no crash report in the log

**Comment by Margatroidu** [comment]
> Crash report? There's no crash report in the log

There was no crash report. The game just permanently froze

**Comment by Margatroidu** [comment]
I will reopen this problem, for I have the same problem again
The game just froze and the logs repeatedly write this text:

```
[11:04:56] [Thread-156/ERROR] [soundphysics]: Deadlock detected, avoiding it by throwing exception
[11:04:56] [Thread-156/ERROR] [soundphysics]: Error while evaluation environment:
java.lang.IllegalStateException: Player's Data Mananger is write locked
	at com.sonicether.soundphysics.SoundPhysics.getPlayerEyeHeight(SoundPhysics.java:444) ~[SoundPhysics.class:?]
	at com.sonicether.soundphysics.SoundPhysics.evaluateEnvironment(SoundPhysics.java:472) [SoundPhysics.class:?]
	at com.sonicether.soundphysics.SoundPhysics.onPlaySound(SoundPhysics.java:279) [SoundPhysics.class:?]
	at com.sonicether.soundphysics.SoundPhysics.onPlaySound(SoundPhysics.java:263) [SoundPhysics.class:?]
	at paulscode.sound.libraries.SourceLWJGLOpenAL.play(SourceLWJGLOpenAL.java:671) [SourceLWJGLOpenAL.class:?]
	at paulscode.sound.Library.play(Library.java:706) [Library.class:?]
	at paulscode.sound.Library.play(Library.java:675) [Library.class:?]
	at paulscode.sound.SoundSystem.CommandPlay(SoundSystem.java:2076) [SoundSystem.class:?]
	at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2599) [SoundSystem.class:?]
	at paulscode.sound.CommandThread.run(CommandThread.java:121) [CommandThread.class:?]
```

And no crash reports

**Comment by Margatroidu** [comment]
Full logs:
[debug.log](https://github.com/user-attachments/files/18227696/debug.log)
[latest.log](https://github.com/user-attachments/files/18227697/latest.log)

**Comment by Margatroidu** [comment]
I can confirm that this error appears on this fork as well
I can tell you how to try to reproduce this error
As I understand it, you just need to install a resource pack for custom sounds and just play with them
And elitra probably has nothing to do with it (but I'm not sure)

**Comment by Margatroidu** [comment]
I think I'd better close this issue and create a new one with more specific information when I encounter freezing already with this fork
